### ISSUE TITLE
DP - Team Member Roles

### ISSUE THREAD

**Issue by Inreet-Kaur** [Inreet-Kaur/capstone#17]

**Comment by PKALXI** [comment]
Looks good perhaps reword:

By adopting a flexible approach to the following roles, we want to ensure
that everyone has the opportunity to lead and adapt their role according to the
project’s need

Otherwise awesome!

**Comment by gkaur034** [comment]
Looks great, it's a great way to organize and the flexibility of rotating the roles would give everyone a chance to explore every aspect of this project.
