### ISSUE TITLE
DP - Project Decomposition & Scheduling

### ISSUE THREAD

**Issue by Inreet-Kaur** [Inreet-Kaur/capstone#19]

**Comment by PKALXI** [comment]
Each project will be scheduled according to the deadlines outlined in the
course outline.

Should be :

Each **TASK** will be scheduled according to the deadlines outlined in the
course outline.

Perhaps itemize the procedure and different dashboards for ease of reading

**Comment by gkaur034** [comment]
The explanation is really good and the chronological order makes it easier to follow. 

Just to mention in general: The issue automatically moves to "Done" section once a pull request is made.
